INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (1, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (2, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (2, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (3, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (3, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (3, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (4, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (4, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (4, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (5, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (5, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (5, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (5, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (5, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (6, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (7, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (7, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (7, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (8, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (9, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (9, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (10, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (10, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (10, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (11, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (11, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (12, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (12, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (13, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (13, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (13, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (14, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (14, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (15, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (15, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (17, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (17, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (17, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (17, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (18, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (18, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (18, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (18, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (18, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (19, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (20, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (20, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (21, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (21, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (22, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (23, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (23, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (23, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (23, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (24, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (24, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (24, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (25, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (26, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (26, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (26, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (27, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (27, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (28, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (28, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (28, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (28, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (29, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (29, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (29, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (29, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (29, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (30, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (30, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (31, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (31, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (31, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (31, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (31, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (32, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (33, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (33, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (35, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (35, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (35, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (35, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (36, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (36, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (37, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (37, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (37, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (38, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (38, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (39, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (39, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (39, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (40, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (40, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (40, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (40, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (41, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (42, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (43, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (43, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (44, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (45, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (45, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (45, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (45, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (45, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (46, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (47, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (47, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (47, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (47, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (48, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (48, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (48, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (48, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (50, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (50, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (50, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (51, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (51, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (52, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (52, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (52, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (52, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (53, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (53, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (53, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (53, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (54, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (54, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (54, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (54, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (55, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (55, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (55, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (55, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (55, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (56, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (57, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (57, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (57, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (58, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (58, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (58, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (59, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (59, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (59, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (59, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (59, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (60, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (61, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (61, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (61, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (63, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (63, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (64, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (65, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (65, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (65, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (66, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (66, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (66, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (66, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (66, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (67, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (67, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (67, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (67, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (67, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (68, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (68, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (68, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (68, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (68, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (69, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (69, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (69, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (70, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (70, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (70, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (71, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (71, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (71, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (71, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (72, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (72, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (72, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (72, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (73, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (73, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (74, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (74, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (74, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (75, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (76, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (76, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (77, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (77, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (78, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (78, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (78, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (78, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (79, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (79, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (79, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (80, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (80, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (80, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (81, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (81, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (81, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (81, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (81, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (82, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (83, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (83, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (83, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (83, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (84, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (84, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (84, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (84, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (85, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (85, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (86, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (87, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (87, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (88, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (88, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (89, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (89, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (89, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (89, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (89, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (89, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (90, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (90, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (91, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (91, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (91, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (92, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (93, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (93, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (93, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (93, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (94, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (94, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (94, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (94, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (95, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (95, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (95, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (95, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (95, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (96, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (97, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (98, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (98, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (98, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (99, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (99, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (99, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (100, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (100, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (101, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (101, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (102, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (102, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (103, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (103, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (103, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (104, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (104, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (104, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (105, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (105, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (106, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (106, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (107, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (108, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (108, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (108, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (109, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (109, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (110, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (110, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (110, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (111, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (111, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (112, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (112, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (112, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (112, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (113, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (114, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (114, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (114, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (115, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (115, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (115, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (116, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (116, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (116, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (116, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (117, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (117, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (117, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (117, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (118, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (118, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (118, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (119, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (119, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (120, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (121, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (121, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (121, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (121, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (121, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (121, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (121, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (122, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (123, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (123, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (123, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (123, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (124, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (124, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (124, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (124, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (124, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (125, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (125, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (125, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (125, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (126, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (128, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (128, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (128, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (129, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (129, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (129, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (130, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (130, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (130, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (131, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (131, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (131, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (132, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (132, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (132, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (132, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (133, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (133, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (133, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (134, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (134, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (134, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (134, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (135, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (136, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (136, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (136, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (138, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (138, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (138, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (139, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (139, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (139, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (139, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (140, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (140, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (141, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (141, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (142, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (143, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (143, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (143, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (143, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (144, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (144, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (144, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (145, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (145, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (146, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (147, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (147, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (148, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (148, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (148, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (148, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (148, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (149, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (149, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (150, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (150, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (150, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (152, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (152, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (152, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (153, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (153, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (153, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (154, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (154, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (154, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (155, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (156, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (156, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (156, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (156, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (157, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (157, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (157, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (158, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (158, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (158, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (158, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (159, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (159, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (160, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (160, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (160, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (161, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (162, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (162, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (162, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (163, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (163, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (163, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (164, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (164, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (164, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (165, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (165, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (166, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (166, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (166, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (166, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (166, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (167, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (167, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (167, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (168, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (169, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (170, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (170, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (171, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (171, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (171, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (171, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (172, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (173, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (173, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (174, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (174, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (174, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (174, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (174, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (174, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (175, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (177, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (177, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (177, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (177, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (177, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (178, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (179, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (179, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (179, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (180, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (180, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (180, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (181, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (182, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (182, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (183, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (183, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (183, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (184, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (185, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (185, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (185, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (185, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (186, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (186, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (187, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (188, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (189, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (189, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (190, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (190, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (190, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (191, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (191, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (191, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (193, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (193, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (193, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (193, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (194, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (194, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (194, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (194, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (195, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (196, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (196, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (197, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (197, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (197, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (197, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (198, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (198, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (199, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (199, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (199, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (200, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (201, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (201, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (201, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (202, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (202, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (202, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (202, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (202, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (202, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (203, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (203, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (203, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (203, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (203, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (205, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (205, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (205, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (205, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (205, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (206, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (206, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (206, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (207, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (207, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (207, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (208, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (209, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (209, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (209, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (209, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (209, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (210, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (210, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (210, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (211, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (211, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (212, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (213, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (213, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (213, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (214, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (214, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (217, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (218, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (218, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (219, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (219, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (219, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (220, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (220, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (221, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (221, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (222, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (222, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (223, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (224, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (224, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (224, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (224, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (225, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (225, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (225, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (226, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (226, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (226, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (227, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (227, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (228, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (228, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (228, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (228, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (229, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (229, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (230, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (230, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (231, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (231, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (233, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (233, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (234, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (234, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (234, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (235, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (235, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (235, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (236, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (237, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (237, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (237, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (237, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (238, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (238, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (239, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (240, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (240, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (241, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (241, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (241, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (241, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (242, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (242, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (242, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (242, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (242, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (243, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (243, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (243, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (243, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (244, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (244, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (244, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (244, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (245, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (245, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (245, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (246, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (247, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (247, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (248, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (248, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (249, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (249, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (249, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (250, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (250, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (251, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (251, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (252, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (252, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (253, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (253, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (253, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (253, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (254, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (255, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (255, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (255, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (257, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (257, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (257, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (257, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (258, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (258, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (258, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (258, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (259, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (259, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (260, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (260, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (260, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (260, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (260, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (260, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (261, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (261, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (262, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (262, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (263, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (263, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (263, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (264, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (264, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (264, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (264, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (265, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (265, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (265, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (266, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (266, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (267, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (267, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (268, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (269, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (270, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (271, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (271, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (271, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (272, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (272, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (273, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (273, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (273, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (274, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (274, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (274, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (274, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (274, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (275, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (275, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (275, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (276, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (276, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (277, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (277, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (277, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (278, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (279, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (280, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (281, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (281, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (282, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (282, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (282, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (282, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (284, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (285, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (285, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (285, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (286, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (286, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (286, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (286, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (287, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (288, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (289, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (289, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (289, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (289, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (290, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (290, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (290, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (290, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (291, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (292, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (292, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (293, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (293, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (293, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (294, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (294, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (294, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (294, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (294, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (294, 'Physical Chemical and Earth Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (295, 'Medical and Health Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (296, 'Economics and Commerce');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (296, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (297, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (297, 'Mathematical Information and Computing Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (298, 'Biological and Biotechnological Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (299, 'Education and Human Society');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (299, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (300, 'Engineering and Environmental Sciences');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (300, 'Humanities and Creative Arts');
INSERT INTO `project_field` (`ID_Project`, `Field_Title`) VALUES (300, 'Mathematical Information and Computing Sciences');


