insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (51, 'Zoolab', 'De-engineered 6th generation alliance', '2011-07-26');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (249, 'Fintone', 'Triple-buffered disintermediate Graphical User Interface', '2015-02-23');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (288, 'Sonsing', 'Optional client-driven architecture', '2012-07-16');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (51, 'Fixflex', 'Open-source executive analyzer', '2012-10-20');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (29, 'Ventosanzap', 'Public-key 24/7 approach', '2015-04-03');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (186, 'Alphazap', 'Open-architected human-resource capacity', '2010-09-01');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (67, 'Biodex', 'Persevering hybrid productivity', '2013-12-26');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (69, 'Span', 'Assimilated heuristic internet solution', '2013-10-12');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (186, 'Stronghold', 'Fully-configurable 24/7 moderator', '2015-04-30');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (82, 'Bitchip', 'Open-source interactive project', '2014-03-18');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (34, 'Bamity', 'User-centric user-facing orchestration', '2012-02-24');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (211, 'Home Ing', 'Synchronised intermediate challenge', '2014-06-30');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (72, 'Flowdesk', 'Right-sized 24/7 help-desk', '2011-05-26');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (183, 'Opela', 'Extended next generation software', '2015-03-05');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (199, 'Zaam-Dox', 'Universal cohesive hub', '2010-08-10');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (88, 'Y-find', 'Implemented national utilisation', '2014-07-25');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (156, 'Otcom', 'Polarised hybrid productivity', '2013-07-13');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (40, 'Temp', 'Programmable needs-based data-warehouse', '2015-01-13');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (17, 'Voyatouch', 'Synergistic clear-thinking productivity', '2011-07-25');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (78, 'Wrapsafe', 'Sharable bifurcated software', '2012-04-03');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (143, 'Toughjoyfax', 'Fully-configurable cohesive leverage', '2010-08-11');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (90, 'Wrapsafe', 'Adaptive zero administration superstructure', '2015-01-02');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (273, 'Voyatouch', 'Object-based executive workforce', '2010-06-19');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (188, 'Transcof', 'Exclusive systemic approach', '2010-10-05');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (28, 'Tampflex', 'Monitored impactful application', '2015-04-15');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (275, 'Greenlam', 'Multi-lateral 4th generation access', '2014-10-25');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (35, 'Greenlam', 'Robust holistic productivity', '2014-11-17');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (273, 'Overhold', 'Managed exuding policy', '2013-05-21');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (298, 'Home Ing', 'Innovative scalable matrices', '2012-03-31');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (283, 'Lotlux', 'Multi-layered directional hardware', '2013-11-13');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (223, 'Transcof', 'De-engineered optimal website', '2015-02-07');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (202, 'Zoolab', 'Distributed didactic data-warehouse', '2011-06-03');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (58, 'Domainer', 'Object-based 5th generation success', '2010-11-02');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (12, 'Otcom', 'Multi-tiered human-resource challenge', '2010-07-13');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (234, 'Zamit', 'Balanced demand-driven service-desk', '2014-11-23');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (155, 'Rank', 'Seamless even-keeled artificial intelligence', '2015-05-01');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (203, 'Viva', 'Function-based attitude-oriented focus group', '2010-09-18');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (158, 'Sonair', 'Diverse encompassing groupware', '2013-05-05');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (267, 'Bitchip', 'Synergistic holistic pricing structure', '2012-08-05');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (78, 'Bytecard', 'Self-enabling 6th generation matrices', '2013-09-17');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (120, 'Stringtough', 'Multi-layered mobile artificial intelligence', '2014-04-12');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (8, 'Hatity', 'Monitored foreground database', '2014-04-01');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (128, 'Stim', 'Polarised intermediate success', '2011-12-22');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (157, 'Stim', 'Reactive zero administration approach', '2014-01-12');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (150, 'Kanlam', 'Compatible mission-critical alliance', '2011-02-18');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (276, 'Stronghold', 'Automated next generation knowledge user', '2013-05-14');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (112, 'Y-find', 'Organic even-keeled toolset', '2011-05-08');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (294, 'Greenlam', 'Fully-configurable motivating firmware', '2012-05-25');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (218, 'Cardguard', 'Distributed human-resource workforce', '2011-05-28');
insert into deliverable (ID_Project, Title, Description, Delivery_Date) values (234, 'Span', 'Virtual upward-trending frame', '2014-05-28');
