insert into program (Branch) values ('Physical, Chemical and Earth Sciences');
insert into program (Branch) values ('Physical, Chemical and Earth Sciences');
insert into program (Branch) values ('Humanities and Creative Arts');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Physical, Chemical and Earth Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Economics and Commerce');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Humanities and Creative Arts');
insert into program (Branch) values ('Mathematical, Information and Computing Sciences');
insert into program (Branch) values ('Biological and Biotechnological Sciences');
insert into program (Branch) values ('Mathematical, Information and Computing Sciences');
insert into program (Branch) values ('Economics and Commerce');
insert into program (Branch) values ('Medical and Health Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Physical, Chemical and Earth Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Humanities and Creative Arts');
insert into program (Branch) values ('Humanities and Creative Arts');
insert into program (Branch) values ('Medical and Health Sciences');
insert into program (Branch) values ('Medical and Health Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Medical and Health Sciences');
insert into program (Branch) values ('Biological and Biotechnological Sciences');
insert into program (Branch) values ('Medical and Health Sciences');
insert into program (Branch) values ('Biological and Biotechnological Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Humanities and Creative Arts');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Biological and Biotechnological Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Medical and Health Sciences');
insert into program (Branch) values ('Humanities and Creative Arts');
insert into program (Branch) values ('Humanities and Creative Arts');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Engineering and Environmental Sciences');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Education and Human Society');
insert into program (Branch) values ('Biological and Biotechnological Sciences');
